name: arslan_services
description: Arslan Services - Home Services Marketplace Pakistan
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  url_launcher: ^6.3.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  socket_io_client: ^2.0.3
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  intl: any
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/
